apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-parameters
data:
  artifactRepositoryAccessKeySecretKey: accesskey
  artifactRepositoryAccessKeySecretName: mlpipeline-minio-artifact
  artifactRepositoryBucket: vf-infdev-ca-nonlive-kf-pipeline-store # {"$kpt-set":"pipelineGCSBucketName"}
  artifactRepositoryEndpoint: minio-service.kubeflow:9000
  artifactRepositoryInsecure: "true"
  artifactRepositoryKeyPrefix: artifacts
  artifactRepositorySecretKeySecretKey: secretkey
  artifactRepositorySecretKeySecretName: mlpipeline-minio-artifact
  clusterDomain: cluster.local
  containerRuntimeExecutor: docker
  executorImage: argoproj/argoexec:v2.3.0
  namespace: kubeflow
