apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: profiles
  app.kubernetes.io/name: profiles
  kustomize.component: profiles
  kf-name: "KUBEFLOWNAME" # {"$kpt-set":"kubeflowName"}
  kf-admin: "KFADMIN" # {"$kpt-set":"kfAdmin"}
  kf-project: "PROJECT" # {"$kpt-set":"project"}
resources:
- ./connor-wilkes
- ./harry-cai
