apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app.kubernetes.io/component: gke-metadata-egress
  app.kubernetes.io/name: gke-metadata-egress
  kustomize.component: gke-metadata-egress
resources:
- gke-metadata-service.yaml
