apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
spec:
  template:
    spec:
      containers:
      - name: katib-db-manager
        env:
        - name: DB_NAME
          value: mysql
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: katib-mysql-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: katib-mysql-secrets
              key: DB_PASSWORD
        - name: KATIB_MYSQL_DB_DATABASE
          value: katib
        - name: KATIB_MYSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: dbHost
        - name: KATIB_MYSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: pipeline-install-config
              key: dbPort
