apiVersion: v1
kind: ServiceAccount
metadata:
  name: profiles-controller-service-account
  annotations:
    iam.gke.io/gcp-service-account: profilecontrollersa # {"$kpt-set":"profile-controller-sa"}
