apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: activator
  namespace: knative-serving
spec:
  rules:
  - services:
    - activator-service.knative-serving.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-activator
  namespace: knative-serving
spec:
  roleRef:
    kind: ServiceRole
    name: activator
  subjects:
  - user: '*'
