apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: autoscaler
  namespace: knative-serving
spec:
  rules:
  - services:
    - autoscaler.knative-serving.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-autoscaler
  namespace: knative-serving
spec:
  roleRef:
    kind: ServiceRole
    name: autoscaler
  subjects:
  - user: '*'
