apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: controller
  namespace: knative-serving
spec:
  rules:
  - services:
    - controller.knative-serving.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-controller
  namespace: knative-serving
spec:
  roleRef:
    kind: ServiceRole
    name: controller
  subjects:
  - user: '*'
