apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: webhook
  namespace: knative-serving
spec:
  rules:
  - services:
    - webhook.knative-serving.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-webhook
  namespace: knative-serving
spec:
  roleRef:
    kind: ServiceRole
    name: webhook
  subjects:
  - user: '*'
