apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: profiles
  app.kubernetes.io/name: profiles
  kustomize.component: profiles
namespace: nicholas-zeolla
resources:
- ./nicholas-zeolla-profile.yaml
- ./psp.yaml
