apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  kf-name: "infdev-nonlive-kf" # {"$kpt-set":"kubeflowName"}
  kf-admin: connor.wilkes # {"$kpt-set":"kfAdmin"}
  kf-project: "vf-infdev-ca-nonlive" # {"$kpt-set":"project"}
patchesStrategicMerge:
- ./kubeflow-gateway/istio-parameters.yaml
resources:
- ../../../../common/kustomize/kubeflow-istio-resources
