apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-headless
  namespace: istio-system
  labels:
    app: jaeger
    jaeger-infra: collector-service
    release: istio
spec:
  ports:
    - name: jaeger-collector-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
  selector:
    app: jaeger
  clusterIP: None