apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app.kubernetes.io/component: jaeger-tracing
  app.kubernetes.io/name: jaeger-tracing
  kustomize.component: jaeger-tracing
resources:
  - agent-service.yaml
  - collector-headless-service.yaml
  - collector-service.yaml
  - deployment.yaml
  - query-service.yaml
  - tracing-service.yaml
  - zipkin-service.yaml
  - service-account.yaml
images:
  - name: docker.io/jaegertracing/all-in-one
