apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: profiles
  app.kubernetes.io/name: profiles
  kustomize.component: profiles
namespace: sobhan-afroosheh
resources:
- ./sobhan-afroosheh-profile.yaml
- ./psp.yaml
