apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sobhan-afroosheh-profile-psp-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: sobhan-afroosheh
roleRef:
  kind: ClusterRole
  name: neuron-psp-cluster-role
  apiGroup: rbac.authorization.k8s.io
