apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  kf-name: "infdev-nonlive-kf" # {"$kpt-set":"kubeflowName"}
  kf-admin: connor.wilkes # {"$kpt-set":"kfAdmin"}
  kf-project: "vf-infdev-ca-nonlive" # {"$kpt-set":"project"}
patchesStrategicMerge:
- ./patches/pipeline-workload-identity-bindings-patch.yaml
- ./patches/profile-controller-workload-identity-patch.yaml
- ./config/pipeline-install-config.yaml
- ./config/workflow-controller-parameters.yaml
- ./config/metadata-db-parameters.yaml
resources:
- ../../../../common/kustomize/kubeflow-applications
images:
#  ../../upstream/application/v3
#  ../../upstream/admission-webhook/overlays/application
- name: gcr.io/kubeflow-images-public/kubernetes-sigs/application
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/kubernetes-sigs/application
  newTag: 1.0-beta
- name: gcr.io/kubeflow-images-public/ingress-setup
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/ingress-setup
  newTag: latest
  #  ../../upstream/namespaces/base
- name: gcr.io/kubeflow-images-public/admission-webhook
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/admission-webhook
  newTag: vmaster-ge5452b6f
  #  ../../upstream/common/centraldashboard/overlays/stacks
- name: gcr.io/kubeflow-images-public/centraldashboard
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/centraldashboard
  newTag: vmaster-g8097cfeb
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/jupyter-web-app
  newTag: vmaster-g845af298
- name: gcr.io/kubeflow-images-public/notebook-controller
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/notebook-controller
  newTag: vmaster-g6eb007d0
  # ../../upstream/profiles/base_v3
- name: gcr.io/kubeflow-images-public/kfam
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/kfam
  newTag: vmaster-g9f3bfd00
- name: gcr.io/kubeflow-images-public/profile-controller
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/profile-controller
  newTag: vmaster-ga49f658f
- name: gcr.io/kubeflow-images-public/pytorch-operator
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/pytorch-operator
  newTag: v1.1.0-gd596e904
- name: gcr.io/spark-operator/spark-operator
  #newName: registry.harbor.vodafone.com/vf-neuron/spark-operator/spark-operator
  newTag: v1beta2-1.1.0-2.4.5
- name: gcr.io/kubeflow-images-public/tf_operator
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/tf_operator
  newTag: vmaster-gda226016
- name: mxjob/mxnet-operator
  #newName: registry.harbor.vodafone.com/vf-neuron/mxnet-operator
  newTag: v1.0.0-20200625
- name: mpioperator/mpi-operator
  #newName: registry.harbor.vodafone.com/vf-neuron/mpi-operator
  newTag: latest
  # ../../upstream/katib/installs/katib-externaldb
- name: docker.io/kubeflowkatib/katib-controller
  newTag: v1beta1-a96ff59
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflowkatib/katib-controller
- name: docker.io/kubeflowkatib/katib-ui
  newTag: v1beta1-a96ff59
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflowkatib/katib-ui
- name: docker.io/kubeflowkatib/katib-db-manager
  newTag: v1beta1-a96ff59
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflowkatib/katib-db-manager
  # ../../upstream/seldon/seldon-core-operator/overlays/application
  # TODO: Edit the helm file for this
- name: gcr.io/kubebuilder/kube-rbac-proxy
  #  newName: registry.harbor.vodafone.com/vf-neuron/kubebuilder/kube-rbac-proxy
  newTag: v0.8.0
- name: gcr.io/kfserving/kfserving-controller
  newName: gcr.io/vf-mc2dev-ca-lab/mirror/kfserving/kfserving-controller
  #  newName: registry.harbor.vodafone.com/vf-neuron/kfserving/kfserving-controller
  newTag: v0.4.1
- name: python
  #newName: registry.harbor.vodafone.com/vf-neuron/python
  newTag: '3.7'
- name: gcr.io/ml-pipeline/cache-server
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/cache-server
  newTag: '1.0.4'
- name: gcr.io/ml-pipeline/cache-deployer
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/cache-deployer
  newTag: '1.0.4'
- name: gcr.io/ml-pipeline/frontend
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/frontend
  newTag: '1.0.4'
- name: gcr.io/ml-pipeline/metadata-writer
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/metadata-writer
  newTag: '1.0.4'
- name: gcr.io/ml-pipeline/api-server
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/api-server
  newTag: '1.0.4'
- name: gcr.io/ml-pipeline/persistenceagent
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/persistenceagent
  newTag: '1.0.4'
- name: gcr.io/ml-pipeline/scheduledworkflow
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/scheduledworkflow
  newTag: '1.0.4'
- name: gcr.io/ml-pipeline/viewer-crd-controller
  #  newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/viewer-crd-controller
  newTag: '1.0.4'
  # argo
- name: argoproj/argoui
  #newName: registry.harbor.vodafone.com/vf-neuron/argoui
  newTag: latest
- name: argoproj/workflow-controller
  #newName: registry.harbor.vodafone.com/vf-neuron/workflow-controller
  newTag: v2.3.0
  # sparkoperator
- name: gcr.io/spark-operator/spark-operator
  #newName: registry.harbor.vodafone.com/vf-neuron/spark-operator/spark-operator
  newTag: v1beta2-1.1.0-2.4.5
  # xgboost-operator
- name: gcr.io/kubeflow-images-public/xgboost-operator
  #  newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/xgboost-operator
  newTag: v0.1.0
- name: gcr.io/ml-pipeline/visualization-server
  #newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/visualization-server
  newTag: '1.0.4'
- name: gcr.io/kubeflow-images-public/metadata
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/metadata
  newTag: v0.1.11
- name: gcr.io/tfx-oss-public/ml_metadata_store_server
  #newName: registry.harbor.vodafone.com/vf-neuron/tfx-oss-public/ml_metadata_store_server
  newTag: v0.21.1
- name: gcr.io/ml-pipeline/envoy
  #newName: registry.harbor.vodafone.com/vf-neuron/ml-pipeline/envoy
  newTag: metadata-grpc-1.0.1
