apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: jeager-tracing-service-account
  namespace: istio-system
  labels:
    app: jaeger
    release: istio
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: kiali-service-account
  namespace: istio-system
  labels:
    app: kiali
    release: istio
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    app: prometheus
    release: istio
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: grafana-service-account
  namespace: istio-system
  labels:
    app: grafana
    release: istio
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: istio-pilot-service-account
  namespace: istio-system
  labels:
    app: istiod
    release: istio
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: istio-reader-service-account
  namespace: istio-system
  labels:
    app: istio-reader
    release: istio
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: istio-egressgateway-service-account
  namespace: istio-system
  labels:
    app: istio-egressgateway
    istio: egressgateway
    release: istio
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: istio-ingressgateway-service-account
  namespace: istio-system
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
    release: istio
