apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway.yaml
- istio-parameters.yaml
namespace: kubeflow
vars:
- name: gatewaySelector
  objref:
    kind: ConfigMap
    name: istio-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.gatewaySelector
- name: hostname
  objref:
    kind: ConfigMap
    name: istio-parameters
    apiVersion: v1
  fieldref:
    fieldPath: data.hostname
configurations:
- params.yaml
