apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: cert-manager-cainjector
  labels:
    app: cainjector
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: cert-manager
  labels:
    app: cert-manager
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: cert-manager-webhook
  labels:
    app: webhook