apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  kf-name: "KUBEFLOWNAME" # {"$kpt-set":"kubeflowName"}
  kf-admin: "KFADMIN" # {"$kpt-set":"kfAdmin"}
  kf-project: "PROJECT" # {"$kpt-set":"project"}
resources:
- ../../../../common/kustomize/istio-local-gateway
images:
- name: docker.io/istio/proxyv2
  #newName: registry.harbor.vodafone.com/vf-neuron/proxyv2
  newTag: 1.5.10-distroless
