apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: harry-cai
spec:
  owner:
    kind: User
    name: harry.cai@vodafone.com
  plugins:
    - kind: WorkloadIdentity
      spec:
        gcpServiceAccount: kf-test@vf-infdev-ca-lab.iam.gserviceaccount.com
