apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-google-iap
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: google-iap
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google-iap
spec:
  host: gstatic.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-google-iap-through-egress-gateway
spec:
  hosts:
    - gstatic.com
  gateways:
    - mesh
    - istio-system/istio-egressgateway
  tls:
    - match:
        - gateways:
            - mesh
          port: 443
          sniHosts:
            - gstatic.com
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: google-iap
            port:
              number: 443
    - match:
        - gateways:
            - istio-system/istio-egressgateway
          port: 443
          sniHosts:
            - gstatic.com
      route:
        - destination:
            host: gstatic.com
            port:
              number: 443
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-iap-service-entry
spec:
  hosts:
    - gstatic.com
  ports:
    - number: 443
      name: tls
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
