apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app.kubernetes.io/component: googleiap-istio-egress
  app.kubernetes.io/name: googleiap-istio-egress
  kustomize.component: googleiap-istio-egress
resources:
- googleiap.yaml
