apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: gpu-driver
  app.kubernetes.io/name: gpu-driver
  kustomize.component: gpu-driver
  application-crd-id: gpu-driver
namespace: kube-system
resources:
- ../../upstream/gcp/gpu-driver/overlays/application
images:
- name: gcr.io/google-containers/pause
  newName: gcr.io/google-containers/pause
  newTag: '2.0'
- name: cos-nvidia-installer
  newName: cos-nvidia-installer
  newTag: fixed
