apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    release: istio
type: Opaque
data:
  username: YWRtaW4= # admin
  passphrase: YWRtaW4= # admin
  oidc-secret: aGR4NDlXN0tNQUMxRlA0WmVZakZIdzFC