apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kf-name: "KUBEFLOWNAME" # {"$kpt-set":"kubeflowName"}
  kf-admin: "KFADMIN" # {"$kpt-set":"kfAdmin"}
  kf-project: "PROJECT" # {"$kpt-set":"project"}
namespace: kubeflow
resources:
- ../../../../common/kustomize/metacontroller
images:
- name: gcr.io/kubeflow-images-public/admission-webhook
  #newName: registry.harbor.vodafone.com/vf-neuron/kubeflow-images-public/admission-webhook
  newTag: vmaster-ge5452b6f
