apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-mgr-psp-role
  namespace: cert-manager
subjects:
# For all service accounts in a particular namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: neuron-psp-cluster-role
  apiGroup: rbac.authorization.k8s.io
