# Role binding which grants access to the app pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: knative-psp-role
  namespace: knative-serving
subjects:
# For all service accounts in a particular namespace
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: knative-serving
roleRef:
  kind: ClusterRole
  name: neuron-psp-cluster-role
  apiGroup: rbac.authorization.k8s.io
