apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app.kubernetes.io/component: istio
  app.kubernetes.io/name: istio
  kustomize.component: istio
resources:
  - istio.yaml
  - cluster-rbac-config.yaml
  - egress-gateway.yaml
  - gcr-io-egress
  - gke-metadata-egress
  - shared-services-egress
  - googleapis-istio-egress
  - istio-external-mysql-egress
  - istio-vf-github-egress
  - health-check-vs.yaml
  - ./monitoring
  - ./config/mysql-params.yaml
configurations:
  - params.yaml
vars:
  - fieldref:
      fieldPath: data.mysqlDNS
    name: mysqlDNS
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: mysql-params
images:
  - name: docker.io/istio/proxyv2
  - name: docker.io/istio/pilot:1.5.10-distroless
