apiVersion: v1
data:
  MYSQL_HOST: "mySQLhost" # {"$kpt-set":"mysqlDNS"}
  MYSQL_DATABASE: metadb
  MYSQL_PORT: "port" # {"$kpt-set":"databasePort"}
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"
kind: ConfigMap
metadata:
  name: metadata-db-parameters
