apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kf-name: "KUBEFLOWNAME" # {"$kpt-set":"kubeflowName"}
  kf-admin: "KFADMIN" # {"$kpt-set":"kfAdmin"}
  kf-project: "PROJECT" # {"$kpt-set":"project"}
resources:
- ../../../../common/kustomize/cert-manager
images:
- name: quay.io/jetstack/cert-manager-controller
  #newName: registry.harbor.vodafone.com/vf-neuron/jetstack/cert-manager-controller
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-webhook
  #newName: registry.harbor.vodafone.com/vf-neuron/jetstack/cert-manager-webhook
  newTag: v0.11.0
- name: quay.io/jetstack/cert-manager-cainjector
  #newName: registry.harbor.vodafone.com/vf-neuron/jetstack/cert-manager-cainjector
  newTag: v0.11.0
