apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: raja-kolli-profile-psp-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
  namespace: raja-kolli
roleRef:
  kind: ClusterRole
  name: neuron-psp-cluster-role
  apiGroup: rbac.authorization.k8s.io
