apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: google-api-entry
spec:
  hosts:
    - www.googleapis.com
  ports:
    - number: 443
      name: tls
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: google-api-entry
spec:
  host: www.googleapis.com
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-google-api-entry
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: google-api-entry
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: googleapis
spec:
  gateways:
    - mesh
    - istio-system/istio-egressgateway
  hosts:
    - "*.googleapis.com"
  tls:
    - match:
        - gateways:
            - mesh
          port: 443
          sniHosts:
            - "*.googleapis.com"
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: google-api-entry
            port:
              number: 443
    - match:
        - gateways:
            - istio-system/istio-egressgateway
          port: 443
          sniHosts:
            - "*.googleapis.com"
      route:
        - destination:
            host: www.googleapis.com
            port:
              number: 443
          weight: 100
