apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-vf-github
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
  - name: vf-github
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: vf-github
spec:
  host: github.vodafone.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-vf-github-through-egress-gateway
spec:
  hosts:
  - github.vodafone.com
  gateways:
  - mesh
  - istio-system/istio-egressgateway
  tls:
  - match:
    - gateways:
      - mesh
      port: 443
      sniHosts:
      - github.vodafone.com
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: vf-github
        port:
          number: 443
  - match:
    - gateways:
      - istio-system/istio-egressgateway
      port: 443
      sniHosts:
      - github.vodafone.com
    route:
    - destination:
        host: github.vodafone.com
        port:
          number: 443
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: vf-github
spec:
  hosts:
  - github.vodafone.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
