apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kf-name: "infdev-lab-kf" # {"$kpt-set":"kubeflowName"}
  kf-admin: connor.wilkes # {"$kpt-set":"kfAdmin"}
  kf-project: "vf-infdev-ca-lab" # {"$kpt-set":"project"}
resources:
- ../../../../common/kustomize/cert-manager
images:
- name: gcr.io/vf-mc2dev-ca-lab/mirror/quay.io/jetstack/cert-manager-controller
  newName: registry.harbor.vodafone.com/vf-neuron/jetstack/cert-manager-controller
  newTag: v0.11.0
- name: gcr.io/vf-mc2dev-ca-lab/mirror/quay.io/jetstack/cert-manager-webhook
  newName: registry.harbor.vodafone.com/vf-neuron/jetstack/cert-manager-webhook
  newTag: v0.11.0
- name: gcr.io/vf-mc2dev-ca-lab/mirror/quay.io/jetstack/cert-manager-cainjector
  newName: registry.harbor.vodafone.com/vf-neuron/jetstack/cert-manager-cainjector
  newTag: v0.11.0
patchesStrategicMerge:
- ./patches/service-account-patch.yaml
