apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
commonLabels:
  kf-name: "infdev-lab-kf" # {"$kpt-set":"kubeflowName"}
  kf-admin: connor.wilkes # {"$kpt-set":"kfAdmin"}
  kf-project: "vf-infdev-ca-lab" # {"$kpt-set":"project"}
resources:
- ./config/kubeflow-config.yaml
- ./service-account.yaml
# Control plane
- ../../upstream/admission-webhook/webhook/v3
- ../../upstream/common/centraldashboard/overlays/stacks
- ../../upstream/kubeflow-roles/base
- ../../upstream/jupyter/jupyter-web-app/base_v3
- ../../upstream/jupyter/notebook-controller/base_v3
- ../../upstream/profiles/base_v3
# Training Operators
- ../../upstream/spark/spark-operator/overlays/application
- ../../upstream/pytorch-job/pytorch-job-crds/overlays/application
- ../../upstream/pytorch-job/pytorch-operator/overlays/application
- ../../upstream/tf-training/tf-job-crds/overlays/application
- ../../upstream/tf-training/tf-job-operator/overlays/application
- ../../upstream/mxnet-job/mxnet-operator/overlays/application
- ../../upstream/mpi-job/mpi-operator/overlays/application
- ../../upstream/xgboost-job/xgboost-operator/overlays/application
# Katib
- ../../upstream/katib/components/katib-crds
- ../../upstream/katib/components/katib-controller
- ../../upstream/katib/components/katib-db-manager
# Pipelines
- ../../upstream/pipeline/installs/multi-user
- ../../upstream/pipeline/upstream/env/gcp/minio-gcs-gateway
- ../../upstream/argo/base_v3
# Serving components
- ../../upstream/seldon/seldon-core-operator/overlays/application
- ../../upstream/kfserving/installs/generic
# Metadata
- ../metadata
# Istio RBAC rules (TODO: Tighten - currently these are 'allow' all)
- ./istio-rbac/admission-webhook-deployment-istio-rbac.yaml
- ./istio-rbac/jupyter-web-app-deployment-istio-rbac.yaml
- ./istio-rbac/katib-controller-istio-rbac.yaml
- ./istio-rbac/katib-db-manager-istio-rbac.yaml
- ./istio-rbac/katib-ui-istio-rbac.yaml
- ./istio-rbac/kubeflow-pipelines-profile-controller-istio-rbac.yaml
- ./istio-rbac/metadata-deployment-istio-rbac.yaml
- ./istio-rbac/metadata-envoy-deployment-istio-rbac.yaml
- ./istio-rbac/metadata-grpc-deployment-istio-rbac.yaml
- ./istio-rbac/minio-istio-rbac.yaml
- ./istio-rbac/notebook-controller-deployment-istio-rbac.yaml
- ./istio-rbac/profiles-deployment-istio-rbac.yaml
- ./istio-rbac/pytorch-operator-istio-rbac.yaml
- ./istio-rbac/seldon-controller-manager-istio-rbac.yaml
- ./istio-rbac/argo-ui-istio-rbac.yaml
- ./istio-rbac/centraldashboard-istio-rbac.yaml
- ./istio-rbac/kfserving-controller-manager-istio-rbac.yaml
- ./istio-rbac/kfserving-controller-manager-metrics-service-istio-rbac.yaml
- ./istio-rbac/kfserving-webhook-server-service-istio-rbac.yaml
- ./istio-rbac/tfjob-operator-istio-rbac.yaml
- ./istio-rbac/xgboost-operator-istio-rbac.yaml
patchesJson6902:
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: mpi-operator
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: kubeflow-pipelines-profile-controller
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: metadata-grpc-deployment
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: mxnet-operator
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: seldon-controller-manager
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: workflow-controller
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: jupyter-web-app-deployment
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: katib-db-manager
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: katib-ui
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: tf-job-operator
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: metadata-envoy-deployment
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: pytorch-operator
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: admission-webhook-deployment
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: profiles-deployment
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: spark-operatorsparkoperator
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: notebook-controller-deployment
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: katib-controller
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: argo-ui
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: Deployment
    name: centraldashboard
    version: v1
    namespace: kubeflow
- patch: |-
    - op: remove
      path: "/spec/template/metadata/annotations/sidecar.istio.io~1inject"
  target:
    group: apps
    kind: StatefulSet
    name: kfserving-controller-manager
    version: v1
    namespace: kubeflow
patchesStrategicMerge:
- ./config/pipeline-install-config.yaml
- ./config/central-dashboard-links-config.yaml
- ./config/profiles-config.yaml
- ./config/mpi-operator-config.yaml
- ./config/workflow-controller-parameters.yaml
- ./config/kfserving-config-map.yaml
- ./patches/common-dashboard-deployment-patch.yaml
- ./patches/pipeline-workload-identity-bindings-patch.yaml
- ./patches/profile-controller-workload-identity-patch.yaml
- ./patches/metadata-envoy-deployment-patch.yaml
- ./patches/minio-gcs-gateway-service-patch.yaml
- ./patches/katib-db-manager-patch.yaml
- ../../upstream/pipeline/upstream/env/gcp/gcp-configurations-patch.yaml
- ./patches/kfserving-controller-manager-metrics-service-patch.yaml
secretGenerator:
- behavior: merge
  envs:
  - ../../../../secrets/pipeline-db-secret.env
  name: mysql-secret
- envs:
  - ../../../../secrets/katib-mysql-secrets.env
  name: katib-mysql-secrets
- name: mlpipeline-minio-artifact
  envs:
  - ../../../../secrets/minio-artifact-secret.env
  behavior: replace
vars:
- fieldref:
    fieldPath: data.clusterDomain
  name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
- fieldref:
    fieldpath: metadata.namespace
  name: katib-ui-namespace
  objref:
    apiVersion: v1
    kind: Service
    name: katib-ui
- fieldref:
    fieldPath: data.registration-flow
  name: registration-flow
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kubeflow-config
images:
#  ../../upstream/application/v3
  #  ../../upstream/admission-webhook/overlays/application
- name: gcr.io/kubeflow-images-public/kubernetes-sigs/application
  newName: gcr.io/kubeflow-images-public/kubernetes-sigs/application
  newTag: 1.0-beta
- name: gcr.io/kubeflow-images-public/ingress-setup
  newName: gcr.io/kubeflow-images-public/ingress-setup
  newTag: latest
  #  ../../upstream/namespaces/base
- name: gcr.io/kubeflow-images-public/admission-webhook
  newName: gcr.io/kubeflow-images-public/admission-webhook
  newTag: vmaster-ge5452b6f
  #  ../../upstream/common/centraldashboard/overlays/stacks
- name: gcr.io/kubeflow-images-public/centraldashboard
  newName: gcr.io/kubeflow-images-public/centraldashboard
  newTag: vmaster-g8097cfeb
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  newName: gcr.io/kubeflow-images-public/jupyter-web-app
  newTag: vmaster-g845af298
- name: gcr.io/kubeflow-images-public/notebook-controller
  newName: gcr.io/kubeflow-images-public/notebook-controller
  newTag: vmaster-g6eb007d0
  # ../../upstream/profiles/base_v3
- name: gcr.io/kubeflow-images-public/kfam
  newName: gcr.io/kubeflow-images-public/kfam
  newTag: vmaster-g9f3bfd00
- name: gcr.io/kubeflow-images-public/profile-controller
  newName: gcr.io/kubeflow-images-public/profile-controller
  newTag: vmaster-ga49f658f
- name: gcr.io/kubeflow-images-public/pytorch-operator
  newName: gcr.io/kubeflow-images-public/pytorch-operator
  newTag: vmaster-g518f9c76
- name: gcr.io/spark-operator/spark-operator
  newName: gcr.io/spark-operator/spark-operator
  newTag: v1beta2-1.1.0-2.4.5
- name: gcr.io/kubeflow-images-public/tf_operator
  newName: gcr.io/kubeflow-images-public/tf_operator
  newTag: vmaster-gda226016
- name: mxjob/mxnet-operator
  newName: kubeflow/mxnet-operator
  newTag: v1.0.0-20200625
- name: mpioperator/mpi-operator
  newName: mpioperator/mpi-operator
  newTag: latest
  # ../../upstream/katib/installs/katib-externaldb
- name: docker.io/kubeflowkatib/katib-controller
  newTag: v1beta1-a96ff59
  newName: docker.io/kubeflowkatib/katib-controller
- name: docker.io/kubeflowkatib/katib-ui
  newTag: v1beta1-a96ff59
  newName: docker.io/kubeflowkatib/katib-ui
- name: docker.io/kubeflowkatib/katib-db-manager
  newTag: v1beta1-a96ff59
  newName: docker.io/kubeflowkatib/katib-db-manager
  # ../../upstream/seldon/seldon-core-operator/overlays/application
  # TODO: Edit the helm file for this
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: gcr.io/vf-mc2dev-ca-lab/mirror/kubebuilder/kube-rbac-proxy
  newTag: v0.4.0
- name: gcr.io/kfserving/kfserving-controller
  newName: gcr.io/vf-mc2dev-ca-lab/mirror/kfserving/kfserving-controller
  newTag: v0.4.1
- name: python
  newName: python
  newTag: '3.7'
- name: gcr.io/ml-pipeline/cache-server
  newName: gcr.io/ml-pipeline/cache-server
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/cache-deployer
  newName: gcr.io/ml-pipeline/cache-deployer
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/frontend
  newName: gcr.io/ml-pipeline/frontend
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/metadata-writer
  newName: gcr.io/ml-pipeline/metadata-writer
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/api-server
  newName: gcr.io/ml-pipeline/api-server
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/persistenceagent
  newName: gcr.io/ml-pipeline/persistenceagent
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: gcr.io/ml-pipeline/scheduledworkflow
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/viewer-crd-controller
  newName: gcr.io/ml-pipeline/viewer-crd-controller
  newTag: 1.4.0-rc.1
- name: gcr.io/ml-pipeline/visualization-server
  newName: gcr.io/ml-pipeline/visualization-server
  newTag: 1.4.0-rc.1
  # argo
- name: argoproj/argoui
  newName: argoproj/argoui
  newTag: latest
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: v2.3.0
  # sparkoperator
- name: gcr.io/spark-operator/spark-operator
  newName: gcr.io/vf-mc2dev-ca-lab/mirror/spark-operator/spark-operator
  newTag: v1beta2-1.1.0-2.4.5
  # xgboost-operator
- name: gcr.io/kubeflow-images-public/xgboost-operator
  newName: gcr.io/kubeflow-images-public/xgboost-operator
  newTag: v0.1.0
