apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: admission-webhook-deployment
  namespace: kubeflow
spec:
  rules:
  - services:
    - admission-webhook-service.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-admission-webhook-deployment
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: admission-webhook-deployment
  subjects:
  - user: '*'
