apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: katib-ui
  namespace: kubeflow
spec:
  rules:
  - services:
    - katib-ui.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-katib-ui
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: katib-ui
  subjects:
  - user: '*'
