apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: kfserving-controller-manager
  namespace: kubeflow
spec:
  rules:
  - services:
    - kfserving-controller-manager-service.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-kfserving-controller-manager
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: kfserving-controller-manager
  subjects:
  - user: '*'
