apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: metadata-deployment
  namespace: kubeflow
spec:
  rules:
  - services:
    - metadata-service.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-metadata-deployment
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: metadata-deployment
  subjects:
  - user: '*'
