apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: minio
  namespace: kubeflow
spec:
  rules:
  - services:
    - minio-service.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-minio
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: minio
  subjects:
  - user: '*'
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ml-pipeline-minio
spec:
  host: minio-service.kubeflow.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
