apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: pytorch-operator
  namespace: kubeflow
spec:
  rules:
  - services:
    - pytorch-operator.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-pytorch-operator
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: pytorch-operator
  subjects:
  - user: '*'
