apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: tf-job-operator
  namespace: kubeflow
spec:
  rules:
    - services:
        - tf-job-operator.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-tf-job-operator
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: tf-job-operator
  subjects:
    - user: '*'