apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: xgboost-operator-deployment
  namespace: kubeflow
spec:
  rules:
    - services:
        - xgboost-operator-service.kubeflow.svc.cluster.local
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-xgboost-operator-deployment
  namespace: kubeflow
spec:
  roleRef:
    kind: ServiceRole
    name: xgboost-operator-deployment
  subjects:
    - user: '*'