apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kf-name: "infdev-lab-kf" # {"$kpt-set":"kubeflowName"}
  kf-admin: connor.wilkes # {"$kpt-set":"kfAdmin"}
  kf-project: "vf-infdev-ca-lab" # {"$kpt-set":"project"}
resources:
- ../../../../common/kustomize/namespaces
