apiVersion: v1
kind: ServiceAccount
metadata:
  name: kf-admin
  annotations:
    iam.gke.io/gcp-service-account: kf-iap-enabler@vf-infdev-ca-nonlive.iam.gserviceaccount.com # {"$kpt-set":"kf-iap-enabler-sa"}
