apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: regcred
metadata:
  name: kf-admin
  annotations:
    iam.gke.io/gcp-service-account: kf-iap-enabler@vf-infdev-ca-lab.iam.gserviceaccount.com # {"$kpt-set":"kf-iap-enabler-sa"}
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: regcred
metadata:
  name: default
  namespace: istio-system
