apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app.kubernetes.io/component: shared-services-egress
  app.kubernetes.io/name: shared-services-egress
  kustomize.component: shared-services-egress
resources:
  - shared-services-egress.yaml
