apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: cluster-local-gateway-service-account
  labels:
    app: cluster-local-gateway
---
apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: regcred
metadata:
  name: istio-multi