apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app.kubernetes.io/component: external-sql-egress
  app.kubernetes.io/name: external-sql-egress
  kustomize.component: external-sql-egress
configurations:
- params.yaml
resources:
- sql.yaml
