apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-gcr-io
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets:
    - name: gcr-io-entry
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: egressgateway-for-gcr-io
spec:
  gateways:
    - mesh
    - istio-system/istio-egressgateway
  hosts:
    - "gcr.io"
  tls:
    - match:
        - gateways:
            - mesh
          port: 443
          sniHosts:
            - "gcr.io"
      route:
        - destination:
            host: istio-egressgateway.istio-system.svc.cluster.local
            subset: gcr-io-entry
            port:
              number: 443
    - match:
        - gateways:
            - istio-system/istio-egressgateway
          port: 443
          sniHosts:
            - "gcr.io"
      route:
        - destination:
            host: "gcr.io"
            port:
              number: 443
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: gcr-io-egress
spec:
  hosts:
    - gcr.io
  ports:
    - number: 443
      name: tls
      protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
