apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: iap-backendconfig
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz/ready
    port: 15020
  securityPolicy:
    name: "kubeflow-security-policy"