apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: cert-manager
  app.kubernetes.io/name: cert-manager
  kustomize.component: cert-manager
  application-crd-id: cert-manager
  kf-name: "infdev-lab-kf" # {"$kpt-set":"kubeflowName"}
  kf-admin: connor.wilkes # {"$kpt-set":"kfAdmin"}
  kf-project: "vf-infdev-ca-lab" # {"$kpt-set":"project"}
namespace: cert-manager
resources:
- ../../upstream/cert-manager/cert-manager/kubeflow-issuer
