apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
commonLabels:
  app.kubernetes.io/component: grafana
  app.kubernetes.io/name: grafana
  kustomize.component: grafana
resources:
  - dashboards.yaml
  - deployment.yaml
  - istio-grafana-config-map.yaml
  - policy.yaml
  - service.yaml
  - ./config/grafana-config.yaml
  - service-account.yaml
secretGenerator:
  - name: grafana-database-config
    envs:
      - ../../../../../../secrets/grafana-mysql-secrets.env
images:
  - name: grafana/grafana:6.7.4